### yum ###
- name: yum -y install java-1.8.0-openjdk java-1.8.0-openjdk-devel
  yum: name={{ item }} state=present
  with_items:
    - java-1.8.0-openjdk
    - java-1.8.0-openjdk-devel
- when: ansible_distribution == 'Amazon'
  name: (Amazon) alternatives --set java /usr/lib/jvm/jre-1.8.0-openjdk.x86_64/bin/java
  shell: alternatives --set java /usr/lib/jvm/jre-1.8.0-openjdk.x86_64/bin/java
